@host = http://localhost:3000
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwMjEzNGFlZS02ZTZiLTQ0OWEtYTkzOC03YzQ0NDUyOTFiYzYiLCJhdWQiOiJqb2huZHVkZSIsImlhdCI6MTc2NTI5NTkzNSwiZXhwIjoxNzY1Mjk1OTQ1fQ.dHZKdEKbMYx_PGgQLu_owzEoCHMe9dVXBEhuo4QnrhM

### [User by ID] Good Request but only if token has not expired
GET {{host}}/user/02134aee-6e6b-449a-a938-7c4445291bc6
Authorization: Bearer {{token}}


### [User by ID] Bad Request
GET {{host}}/user/bad-user-request

### [Login] Auth OK
POST {{host}}/auth/login
Content-Type: application/json

{
    "username":"johndude",
    "password":"testkey" 
}

### [Login] Auth fail
POST {{host}}/auth/login
Content-Type: application/json

{
    "username":"johndude",
    "password":"notthekey" 
}